[build]
base = "/Users/volodymyr/Documents/Github/travaux-asphaltage"
command = "npm run build"
publish = "/Users/volodymyr/Documents/Github/travaux-asphaltage/build"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200