  build:
    base: /Users/volodymyr/Documents/Github/travaux-asphaltage
    command: npm run build
    commandOrigin: config
    publish: /Users/volodymyr/Documents/Github/travaux-asphaltage/build
    publishOrigin: config
  redirects:
    - from: /*
      status: 200
      to: /index.html
  redirectsOrigin: config